/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import com.digitalpersona.onetouch.capture.DPFPCapture;
import dto.Aula;
import dto.Grupo;
import dto.Usuario;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sergio
 */
public class Asistencia extends javax.swing.JFrame {
 private tomarAsistencia myAsis;
 private Usuario e;
 private String Aula;
 private ArrayList<String> codigoGrupos;


 
 
    /**
     * Creates new form registroAsistencia
     */
    public Asistencia(tomarAsistencia form,Usuario e) {
        initComponents();
         this.setTitle("Registra Asistencia");
        this.setLocationRelativeTo(null);
        this.e=e;
        this.codigoGrupos=new ArrayList<String>();
        this.txtUsuario.setText(e.getNombre());
        ArrayList<Aula> aulas;
        ArrayList<Grupo> grupos;
        this.ingresarFoto(e.getFoto());
     try {
         aulas = form.getMyNegocio().mostrarAulas();
         grupos=form.getMyNegocio().devolverGrupo();
         
           for(Aula a :aulas){
                   this.aula.addItem(a.getNombre());
                   } 
           for(Grupo g:grupos){
                  this.codigoGrupos.add(g.getIdGrupo());
                  this.grupos.addItem(g.getNombre());
           }  
                  this.grupos.addItem("No aplica");
     } catch (SQLException ex1) {
         Logger.getLogger(Asistencia.class.getName()).log(Level.SEVERE, null, ex1);
     }
    
        this.myAsis=form;
      
    }
    
    private void ingresarFoto(InputStream f){
                       
                         if(f==null){
                        this.foto.setText("SIN FOTO");
                        return;
                        }     
           try {
          Image I=  ImageIO.read(f);
          Icon icono=new ImageIcon(I.getScaledInstance(foto.getWidth(),foto.getHeight(),Image.SCALE_DEFAULT));
          this.foto.setIcon(icono);
        } catch (IOException ex) {
            Logger.getLogger(registroEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aula = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        registrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        Grupo = new javax.swing.JLabel();
        grupos = new javax.swing.JComboBox<>();
        foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ASISTENCIA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("AULA:");

        aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aulaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("DESCRIPCION");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("USUARIO :");

        txtUsuario.setEnabled(false);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        Grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Grupo.setText("Grupo Investigacion:");

        foto.setText("               ");
        foto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(109, 109, 109)
                        .addComponent(aula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(cancelar)
                        .addGap(5, 5, 5)
                        .addComponent(registrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Grupo)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Grupo))
                    .addComponent(grupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelar)
                    .addComponent(registrar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
               int valor=-1; 
        try {
            
               if(!this.grupos.getSelectedItem().toString().equals("No aplica")){
                 valor=Integer.parseInt(this.codigoGrupos.get(this.grupos.getSelectedIndex()));
               }
              String descripcion=this.txtDescripcion.getText();
              
               if(descripcion.isEmpty()){
                   JOptionPane.showMessageDialog(null,"Debe ingresar proposito de entrada");
                   return;
               }
             this.setVisible(false);
            if (this.myAsis.getMyNegocio().registrarAsistenciaPrograma(this.aula.getSelectedItem().toString(),descripcion, e,(valor))) {
                JOptionPane.showMessageDialog(null, "¡Se registro la asistencia!");
                String path = "/imagenes/limpiar.jpeg";
              //  this.myAsis.lector.stopCapture();
                URL url = this.getClass().getResource(path);
                ImageIcon icon = new ImageIcon(url);
                this.myAsis.getImagen1().setIcon(icon);
                this.myAsis.iniciarTodo();
                this.myAsis.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar la asistencia");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Asistencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_registrarActionPerformed

   
    
    private void aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aulaActionPerformed
                 
    }//GEN-LAST:event_aulaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
         this.setVisible(false);
         String path = "/imagenes/limpiar.jpeg";  
         URL url = this.getClass().getResource(path);
         ImageIcon icon = new ImageIcon(url);
         this.myAsis.getImagen1().setIcon(icon);
         this.myAsis.iniciarTodo();
         this.myAsis.setVisible(true);
        
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Grupo;
    private javax.swing.JComboBox<String> aula;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel foto;
    private javax.swing.JComboBox<String> grupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registrar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
