/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Negocio.Huella;
import Negocio.Negocio;
import java.io.IOException;
import java.io.PrintWriter;

import com.digitalpersona.onetouch.DPFPGlobal;
import com.digitalpersona.onetouch.DPFPSample;
import com.digitalpersona.onetouch.capture.DPFPCapture;
import com.digitalpersona.onetouch.capture.event.DPFPDataAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPDataEvent;
import com.digitalpersona.onetouch.capture.event.DPFPErrorAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPErrorEvent;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusEvent;
import com.digitalpersona.onetouch.capture.event.DPFPSensorAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPSensorEvent;
import dto.Usuario;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
/**
 *
 * @author sergio
 */
public class registroEstudiante extends javax.swing.JFrame implements comunJFrame {

    private DPFPCapture lector = DPFPGlobal.getCaptureFactory().createCapture();
    private String mensaje;
    private byte[] actual=null;
    public boolean sw = false;
    registroUsuarios r;
    InputStream foto=null;
    BufferedImage f;
    
    /**
     * Creates new form registroUsuario
     */
    public registroEstudiante(registroUsuarios r) {       
        initComponents();
         this.setTitle("Registrar Estudiante");
        this.r=r;
        if(r.getMyAsistencia().getImagenHuella()!=null){
         this.DibujarHuella(r.getMyAsistencia().getImagenHuella());
        }
        this.actual=r.getMyAsistencia().getActual();
        this.setLocationRelativeTo(null);
        this.setSize(315,540);
       
      
    }

   

    
    public void DibujarHuella(Image image){
        this.imagen.setIcon(new ImageIcon(
                image.getScaledInstance(this.imagen.getWidth(),this.imagen.getHeight(), image.SCALE_DEFAULT)
        ));
        repaint();
    }
     
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Estudiante = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        imagen = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        cargarFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("REGISTRAR ESTUDIANTE ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Codigo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText(" Huella:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        Estudiante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Estudiante.setText("                  SIN FOTO");
        Estudiante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 170, 140));

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 210, -1));

        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 130, 110));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        cargarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camara2.png"))); // NOI18N
        cargarFoto.setText("Tomar");
        cargarFoto.setToolTipText("Toma la foto aca !");
        cargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFotoActionPerformed(evt);
            }
        });
        getContentPane().add(cargarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
       
        String cedula=this.txtCedula.getText();
        String codigo=this.txtCodigo.getText();
        String nombre=this.txtNombre.getText();
        String telefono=this.txtTelefono.getText();
        byte[] huella=null;
        
                        if(cedula.isEmpty()||codigo.isEmpty()||nombre.isEmpty()||telefono.isEmpty()){
                        JOptionPane.showMessageDialog(null,"¡Digite todos los campos!");
                        return;
                        }
                       
         //cedula no mas de 10 digitos
         
                        if(cedula.length()>10){
                        JOptionPane.showMessageDialog(null,"¡Solo puede tener 10 digitos la cedula!");
                        return;
                        }
                        
         // Codigo  no mas de 10 
         
                        if(codigo.length()>10){
                        JOptionPane.showMessageDialog(null,"¡Limite de longitud de codigo hasta 10 !");
                        return;
                        }
        //telefono  no mas de 10 digitos 
                        if(telefono.length()>10){
                        JOptionPane.showMessageDialog(null,"¡Limite de longitud del telefono hasta 10!");
                        return;
                        }
        // en caso que estemos tratando del lado sin huellero
                         if(this.actual!=null){
                         huella=actual;
                         }
                     
        Usuario e=new Usuario(cedula,codigo,huella,nombre,"Estudiante",null,null,null,telefono,foto);
        
        try {
            if(this.r.getMyAsistencia().getMyNegocio().registrarUsuario(e)){
            JOptionPane.showMessageDialog(null,"¡registro Exitoso!");
            this.setVisible(false);
            
                                   if(f!=null){
             ByteArrayOutputStream out = new ByteArrayOutputStream();
             ImageIO.write(f,"jpg",new File("test.png"));
             ImageIO.write((RenderedImage) f,"jpg", out);
             InputStream in = new ByteArrayInputStream(out.toByteArray());
             e.setFoto(in);
                                   }
            Asistencia form=new Asistencia(this.r.getMyAsistencia(),e);
            form.setVisible(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(registroEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
        
    }//GEN-LAST:event_registrarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.setVisible(false);
        this.r.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void cargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFotoActionPerformed
        Webcam obj=new Webcam(this);
    }//GEN-LAST:event_cargarFotoActionPerformed

    
    private String parseHuella(byte [] huella){
        String cad="";     
            for(int i=0;i<huella.length;i++){
              cad+=huella[i]+",";
            }
            return cad;
    }
    
  
    
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estudiante;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cargarFoto;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

   

    @Override
    public void incluirImagen(InputStream f) {
            try {
          Image I=  ImageIO.read(f);
          Icon icono=new ImageIcon(I.getScaledInstance(Estudiante.getWidth(),Estudiante.getHeight(),Image.SCALE_DEFAULT));
          this.Estudiante.setIcon(icono);
        } catch (IOException ex) {
            Logger.getLogger(registroEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    }

    
    @Override
    public void incluirFoto(BufferedImage image) throws IOException {
     this.f=image;
     ByteArrayOutputStream out = new ByteArrayOutputStream();
     ImageIO.write(image,"jpg",new File("test.png"));
     ImageIO.write((RenderedImage) image,"jpg", out);
     InputStream in = new ByteArrayInputStream(out.toByteArray());
      this.foto=in;
    }

  
}
